services:
  excellentcvwriter.api:
    image: ${DOCKER_REGISTRY-}excellentcvwriter
    container_name: ExcellentCvWriter.Api
    build:
      context: .
      dockerfile: ExcellentCvWriter.Api/Dockerfile
  excellentcvwriter-db:
    image: postgres:latest
    container_name: ExcellentCvWriter.Db
    environment:
      - POSTGRES_DB=excellentcvwriter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  excellentcvwriter-idp:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    container_name: ExcellentCvWriter.Identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/excellentcvwriter-realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/excellentcvwriter-realm-export.json:/tmp/excellentcvwriter-realm-export.json
    ports:
      - 18080:8080
  excellentcvwriter-seq:
    image: datalust/seq:latest
    container_name: ExcellentCvWriter.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80