version: '3.4'

services:
  excellentcvwriter.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro